### ISSUE TITLE
Most endpoints are status code 200

### ISSUE THREAD

**Issue by johmicd** [ocas/InternationalSis#65]
It would be nice to have more information when calling the API and get back the appropriate HTTP status.

curl -sS https://internationalsisapi-ext.dev.ontariocolleges.ca/swagger/v1/swagger.json | jq -r '[.paths[][].responses?| keys?| .[] ]| map( select( test("^x-") | not ))| group_by(.) | map( { code: .[0], count: length })| sort_by(-.count)| map( .code + "\t" + (.count | tostring) )[]'
200	40
409	1

of all your endpoints only 1 returns something other than 200 
delete /api/v1/intakes/{intakeSisIdentifier} 

Can this be changed?

**Comment by jandresvalencia** [comment]
thanks for the feedback @johmicd I will be checking it and getting back to you with a response

**Comment by jandresvalencia** [comment]
UAT5 (IR13) is going to have this fixed in EXT and it is going to be included in IR13
